### ISSUE TITLE
BWT Perla One v.20018

### ISSUE THREAD

**Issue by Prophet955** [dkarv/hacs-bwt-perla#7]
Hello Github community

I have a BWT Perla one softening system

I'm currently still on version 2.0018
The app says that I am on the latest firmware, are the newer beta firmwares? or how did you get the new firmware?

Can I update to 2.02xx?
Always read from people that they have a BWT Perl system.

What data do I have to provide to BWT?

Request for feedback

Thanks

**Comment by dkarv** [comment]
Hello,

the firmware is still in beta. You can ask the support for the latest firmware and it will be updated remotely.
I only had to include my device serial number in the request. One email address used to contact BWT in the past is mentioned here: https://community.home-assistant.io/t/bwt-best-water-tech-nology-support/270745/118

I'm not sure if the integration works out of the box on Perla One devices. Probably I need to do some adjustments due to the fact it only has one column. Happy to adjust it once you have the new firmware and can supply me with test data.
